apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: dalmation
  name: dalmation
spec:
  replicas: 1
  selector:
    matchLabels:
      app: dalmation
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: dalmation
    spec:
      containers:
      - image: redis
        name: redis
        resources:
          limits:
            cpu: 200m
            memory: 512Mi
status: {}
